### ISSUE TITLE
How to visualize the 3D indoor scenes?

### ISSUE THREAD

**Issue by chenguolin** [weixi-feng/LayoutGPT#1]
Hello, I would like to express my appreciation for your admirable work. I must say that the visualizations in the paper are quite impressive. I am curious about how you created the 3D indoor scenes. Would it be possible for you to share the codes or scripts that you used? I would be grateful. Thank you.

BTW, may I ask about the timeline for open-sourcing?

**Comment by weixi-feng** [comment]
Hi Chenguo,

Thank you for your interest in our work. For visualization figures in the paper, I simply used Blender to manually create each of them. But I believe you can also write Python to automatically render every scene. I will see if I have time to write a script for that. 

We are cleaning our code and will release everything within a week or two. Please stay tuned and thanks for your patience. 

Weixi
