### ISSUE TITLE
Question about prepare data

### ISSUE THREAD

**Issue by huangpan2507** [weixi-feng/LayoutGPT#11]
Hi，Thank you for your amazing job. I would like to try this layoutGPT for 3D indoor scene generation. So, do I need to do these steps below? 
1. Download and unzip 3D-FRONT.zip and 3D-FUTURE-model.zip
2. Preprocess the scenes to generate ground truth views
Looking forward to your response, TKS!

**Comment by weixi-feng** [comment]
Hi,

Thank you for your interest and patience. Yes, these are the two steps to prepare 3D layout data.

I checked the licenses of these two datasets and I think I can release the [pre-processed data](https://drive.google.com/file/d/1E0CdPYf1ZpRSfGaXCqa-hbll2Z-KrSrf/view?usp=drive_link) for your convenience. (Of course, you are still welcome to start from preprocessing and give credit to these great datasets.) I will update the README later with caveats for using our processed data. 

Please do let me know if you have further questions.
