### ISSUE TITLE
Question about your supporting set

### ISSUE THREAD

**Issue by samsara-ku** [weixi-feng/LayoutGPT#13]
I cannot find any information about your supporting set, which is `NSR-1K/counting/counting.train.json`.

The only thing I know is it is extracted from the MSCOCO-2017 dataset.

Could you give me more specific information about this json file? (i.e. how you choose some images)

**Comment by weixi-feng** [comment]
Hi,

Thank you for your interest. The counting set is created after a few filtering steps. For template-based examples, we collect images where all bboxes belong to one/two categories. Then we create captions using templates. For natural captions, we make sure that all bbox categories appear in the COCO captions to avoid the original misalignment between captions and bbox annotations. 

Please let me know if this helps.
