### ISSUE TITLE
missing dataset_stats.txt file in preprocessed dataset

### ISSUE THREAD

**Issue by KunalMGupta** [weixi-feng/LayoutGPT#15]
Hi, 

I am trying to run LayoutGPT on indoor scene generation and used the preprocessing [dataset](https://drive.google.com/file/d/1NV3pmRpWcehPO5iKJPmShsRp_lNbxJuK/view?usp=sharing) that you provided. Unfortunately, it seems that it is missing a file "dataset_stats.txt" which is called [here](https://github.com/weixi-feng/LayoutGPT/blob/9404c3c04853594bc41d25cce10b74f2218f97fb/run_layoutgpt_3d.py#L259). Can you please provide the missing files for the preprocessed dataset?

Thanks!

**Comment by user432** [comment]
+1, I've just setup the repository and ran the run_layoutgpt_3d.py file. Seems like, a file is missing. @weixi-feng can you help us with this. Thanks!

**Comment by weixi-feng** [comment]
Hi,

Sorry for the bug. `--dataset_dir` should be set to `./ATISS/data_output/bedroom` or `./ATISS/data_output/livingroom`. Each room type has its own dataset_stats.txt in the folder. I will update the code and Readme soon.

**Comment by user432** [comment]
Hi @weixi-feng, I think the below two changes in run_layout_3d.py are enough.
![Screenshot from 2023-12-05 10-18-34](https://github.com/weixi-feng/LayoutGPT/assets/39729332/eda7bb6b-3959-4103-8aee-4143d1668b98)
