### ISSUE TITLE
Are the CSS structures an input along with the Condition and the image? How are the CSS structures for an examplr retrieved?

### ISSUE THREAD

**Issue by SalehAhmad1** [weixi-feng/LayoutGPT#3]
I have a couple of questions regarding the usage and retrieval of CSS structures in conjunction with conditions and images. I would appreciate some clarification on the following points:

1. Are CSS structures considered as an input alongside conditions and images? If so, how are they incorporated into the overall system?
2. Can you please provide guidance on how to retrieve CSS structures for a specific example or scenario? What are the recommended methods or resources for accessing and utilizing CSS structures effectively?

salehahmad2106@gmail.com
[Saleh Ahmad Github](www.github.com/SalehAhmad1)

**Comment by weixi-feng** [comment]
I am not sure if I fully understand your questions. But basically:
1. Yes, the 2D/3D bounding boxes are represented in the CSS format and input to the LLMs. It simply constructs a plain sequence of values (e.g. [x, y, w, h] in 2d layouts) as a string with a certain format. 
2. The CSS structures are not retrieved but applied to represent retrieved exemplars. 
Please let me know if I have answered your concerns.

**Comment by weixi-feng** [comment]
Hi,

So the outputs of LLMs are in the same structure (CSS) as the in-context exemplars, representing layouts (basically bounding boxes) in 2D or 3D spaces. The properties represent the coordinates or sizes of the bounding boxes.
