### ISSUE TITLE
 Unable to download backbone

### ISSUE THREAD

**Issue by pcxdi** [weixi-feng/LayoutGPT#7]
I downloaded the backbone through the link and cannot proceed with the download due to permission reasons
The error display is as follows：
 wget https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/models/swin_large_patch4_window12_384_22k.pth -O swin_large_patch4_window12_384_22k.pth
wget : PublicAccessNotPermittedPublic access is not permitted on this storage account. RequestId:54b491d5-a01e-0070-1f81-cb068d000000 Time:2023-08-10T11:57:32.7421018Z

**Comment by weixi-feng** [comment]
I think you can download from the [original swin transformer repo](https://github.com/microsoft/Swin-Transformer#main-results-on-imagenet-with-pretrained-models). I think [this](https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth) should be the same checkpoint as the one provided by GLIP.
